//! Declarative parser for macro attributes.
//!
//! This module uses `darling` to parse `#[mapper(...)]` and `#[derive(...)]`
//! attributes from structs and enums. It translates raw parser AST options
//! (like [`MapperOpts`]) into verified mappings (such as [`MappingSpec`]).

// #![allow(
//     clippy::redundant_closure_for_method_calls,
//     reason = "explicit closures are preferred over Spanned::span method paths for readability"
// )]
#![expect(
    clippy::if_not_else,
    clippy::absolute_paths,
    clippy::min_ident_chars,
    clippy::needless_continue,
    reason = "warnings originate within code generated by darling macros"
)]

use darling::{
    FromDeriveInput, FromField, FromMeta, FromVariant,
    ast::{Data, Fields},
    util::{Flag, Override, SpannedValue},
};
use syn::{Error, Expr, Generics, Ident, Type, Visibility, parse_quote, spanned::Spanned as _};

use crate::{
    input::{
        AddedField, BaseData, BaseField, BaseVariant, ConversionOptions, DeriveConfig, FieldMapping, FieldMappings,
        Located, MappingSpec, SkippedField, TransformHint, VariantMapping, VariantMappings,
    },
    type_path_ext::TypePathWrapper,
};

#[derive(Debug, FromDeriveInput)]
#[darling(attributes(mapper), supports(struct_named, struct_newtype, struct_tuple, enum_any))]
pub(crate) struct MapperOpts {
    /// The identifier of the passed-in type.
    ident: Ident,
    /// The generics of the passed-in type.
    generics: Generics,
    /// The body of the passed-in type.
    data: Data<VariantReceiver, FieldReceiver>,

    #[darling(default, multiple, rename = "derive")]
    items: Vec<ItemInput>,

    /// Path of the struct or enum.
    #[darling(default, rename = "ty")]
    path: Option<SpannedValue<TypePathWrapper>>,
    /// Whether to derive [`From`] the type to self.
    #[darling(default)]
    from: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether to derive [`From`] self to the type.
    #[darling(default)]
    into: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether to derive [`TryFrom`] the type to self.
    #[darling(default)]
    try_from: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether to derive [`TryFrom`] self to the type.
    #[darling(default)]
    try_into: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether the other type have some additional variants/fields.
    #[darling(default, multiple)]
    add: Vec<AddInput>,
    /// Whether to ignore all extra fields/variants of the other type.
    #[darling(default)]
    ignore_extra: SpannedValue<Flag>,
}

#[derive(Debug, FromMeta, Clone)]
struct ItemInput {
    /// Path of the struct or enum.
    #[darling(rename = "ty")]
    path: SpannedValue<TypePathWrapper>,
    /// Whether to derive [`From`] the type to self.
    #[darling(default)]
    from: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether to derive [`From`] self to the type.
    #[darling(default)]
    into: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether to derive [`TryFrom`] the type to self.
    #[darling(default)]
    try_from: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether to derive [`TryFrom`] self to the type.
    #[darling(default)]
    try_into: Option<SpannedValue<Override<DeriveInput>>>,
    /// Whether the other type have some additional variants/fields.
    #[darling(default, multiple)]
    add: Vec<AddInput>,
    /// Whether to ignore all extra fields/variants of the other type.
    #[darling(default)]
    ignore_extra: SpannedValue<Flag>,
}

#[derive(Debug, FromVariant, Clone)]
#[darling(attributes(mapper))]
struct VariantReceiver {
    /// The identifier of the passed-in variant.
    ident: Ident,
    /// For a variant such as `Example = 2`, the `2`.
    discriminant: Option<Expr>,
    /// The fields associated with the variant.
    fields: Fields<FieldReceiver>,

    #[darling(default, multiple, rename = "when")]
    items: Vec<ItemVariantInput>,

    /// Path of the struct or enum to derive.
    #[darling(default, rename = "ty")]
    path: Option<SpannedValue<TypePathWrapper>>,
    /// To rename the variant.
    #[darling(default)]
    rename: Option<SpannedValue<Ident>>,
    /// Whether the other type have some additional fields on the variant.
    #[darling(default, multiple)]
    add: Vec<AddInput>,
    /// To skip this variant when deriving (defaults to `false`).
    #[darling(default)]
    skip: Option<SpannedValue<Override<SkipInput>>>,
    /// Whether to ignore all extra fields of the other variant.
    #[darling(default)]
    ignore_extra: SpannedValue<Flag>,
}
macro_field_utils::variant_info!(VariantReceiver, FieldReceiver);

#[derive(Debug, FromMeta, Clone)]
struct ItemVariantInput {
    /// Path of the struct or enum to derive.
    #[darling(rename = "ty")]
    path: SpannedValue<TypePathWrapper>,
    /// To rename the variant.
    #[darling(default)]
    rename: Option<SpannedValue<Ident>>,
    /// Whether the other type have some additional fields on the variant.
    #[darling(default, multiple)]
    add: Vec<AddInput>,
    /// To skip this variant when deriving (defaults to `false`).
    #[darling(default)]
    skip: Option<SpannedValue<Override<SkipInput>>>,
    /// Whether to ignore all extra fields of the other variant.
    #[darling(default)]
    ignore_extra: SpannedValue<Flag>,
}

#[derive(Debug, FromField, Clone)]
#[darling(attributes(mapper))]
struct FieldReceiver {
    /// The identifier of the passed-in field, or [None] for tuple fields.
    ident: Option<Ident>,
    /// The visibility of the passed-in field.
    vis: Visibility,
    /// The type of the passed-in field.
    ty: Type,

    #[darling(default, multiple, rename = "when")]
    items: Vec<ItemFieldInput>,

    /// Path of the struct or enum to derive.
    #[darling(default, rename = "ty")]
    path: Option<SpannedValue<TypePathWrapper>>,
    /// To rename the field.
    #[darling(default)]
    rename: Option<SpannedValue<Ident>>,
    /// To skip this field when deriving (defaults to `false`).
    #[darling(default)]
    skip: Option<SpannedValue<Override<SkipInput>>>,
    /// To use another source generic type for mapping.
    #[darling(default)]
    other_ty: Option<SpannedValue<Ident>>,
    /// Mapper hints.
    #[darling(flatten)]
    hint: MapperHint,
    /// Error expression to map conversion failures (error erasure), only valid for `try_from` / `try_into`.
    #[darling(default)]
    err: Option<SpannedValue<Expr>>,
    /// Error mapping expression to preserve/map the source error, only valid for `try_from` / `try_into`.
    #[darling(default)]
    err_with: Option<SpannedValue<Expr>>,
}
macro_field_utils::field_info!(FieldReceiver);

#[derive(Debug, FromMeta, Clone)]
struct ItemFieldInput {
    /// Path of the struct or enum to derive.
    #[darling(rename = "ty")]
    path: SpannedValue<TypePathWrapper>,
    /// To rename the field.
    #[darling(default)]
    rename: Option<SpannedValue<Ident>>,
    /// To skip this field when deriving (defaults to `false`).
    #[darling(default)]
    skip: Option<SpannedValue<Override<SkipInput>>>,
    /// To use another source generic type for mapping.
    #[darling(default)]
    other_ty: Option<SpannedValue<Ident>>,
    /// Mapper hints.
    #[darling(flatten)]
    hint: MapperHint,
    /// Error expression to map conversion failures (error erasure), only valid for `try_from` / `try_into`.
    #[darling(default)]
    err: Option<SpannedValue<Expr>>,
    /// Error mapping expression to preserve/map the source error, only valid for `try_from` / `try_into`.
    #[darling(default)]
    err_with: Option<SpannedValue<Expr>>,
}

#[derive(Debug, FromMeta, Clone, Default)]
struct MapperHint {
    /// To use some function to map the values.
    #[darling(default)]
    with: Option<SpannedValue<Expr>>,
    /// To use some function to map the values.
    #[darling(default)]
    into_with: Option<SpannedValue<Expr>>,
    /// To use some function to map the values.
    #[darling(default)]
    from_with: Option<SpannedValue<Expr>>,
    /// Whether the field is an option.
    #[darling(default)]
    opt: Option<SpannedValue<Override<Box<MapperHint>>>>,
    /// Wether the field is an iterator.
    #[darling(default)]
    iter: Option<SpannedValue<Override<Box<MapperHint>>>>,
    /// Wether the field is a HashMap-like iter.
    #[darling(default)]
    map: Option<SpannedValue<Override<Box<MapperHint>>>>,
    /// Whether the field is boxed on both sides.
    #[darling(default)]
    boxed: Option<SpannedValue<Override<Box<MapperHint>>>>,
    /// Whether the target field is boxed and the source is not.
    #[darling(default, rename = "box")]
    r#box: Option<SpannedValue<Override<Box<MapperHint>>>>,
    /// Whether the source field is boxed and the target is not.
    #[darling(default)]
    unbox: Option<SpannedValue<Override<Box<MapperHint>>>>,
}

#[derive(Debug, FromMeta, Clone)]
struct DeriveInput {
    /// Whether the derive has external properties or not (name of the custom function if populated).
    #[darling(default)]
    custom: Option<SpannedValue<Override<Ident>>>,
    /// Explicit target error type for fallible conversions.
    #[darling(default)]
    err: Option<TypePathWrapper>,
    /// Whether to accumulate errors instead of short-circuiting, optionally with a custom accumulator type.
    #[darling(default)]
    accumulate: Option<SpannedValue<Override<TypePathWrapper>>>,
}

#[derive(Debug, FromMeta, Clone)]
struct AddInput {
    /// Name of the ignored field or variant.
    field: SpannedValue<Ident>,
    /// Type of the field.
    #[darling(default)]
    ty: Option<SpannedValue<TypePathWrapper>>,
    /// Default value for the field.
    #[darling(default)]
    default: Option<SpannedValue<Override<DefaultInput>>>,
}

#[derive(Debug, FromMeta, Clone)]
struct DefaultInput {
    /// The default value expression.
    value: Expr,
}

#[derive(Debug, FromMeta, Clone)]
struct SkipInput {
    /// Default value for the field.
    #[darling(default)]
    default: Option<SpannedValue<Override<DefaultInput>>>,
}

impl TryFrom<MapperOpts> for MappingSpec {
    type Error = Error;

    fn try_from(opts: MapperOpts) -> Result<Self, Self::Error> {
        let MapperOpts {
            ident: _,
            generics: _,
            data: _,
            items: _,
            path: opts_path,
            from: opts_from,
            into: opts_into,
            try_from: opts_try_from,
            try_into: opts_try_into,
            add: opts_add,
            ignore_extra: opts_ignore_extra,
        } = &opts;

        let has_single_type_opts = opts_path.is_some()
            || opts_from.is_some()
            || opts_into.is_some()
            || opts_try_from.is_some()
            || opts_try_into.is_some()
            || !opts_add.is_empty()
            || opts_ignore_extra.is_present();

        let has_multi_type = !opts.items.is_empty();

        if has_single_type_opts && has_multi_type {
            let err_span = opts
                .path
                .as_ref()
                .map(SpannedValue::span)
                .or_else(|| opts.from.as_ref().map(SpannedValue::span))
                .or_else(|| opts.into.as_ref().map(SpannedValue::span))
                .or_else(|| opts.try_from.as_ref().map(SpannedValue::span))
                .or_else(|| opts.try_into.as_ref().map(SpannedValue::span))
                .or_else(|| opts.add.first().map(|a| a.field.span()))
                .unwrap_or_else(|| opts.ident.span());

            return Err(Error::new(
                err_span,
                "Cannot mix single-type attributes directly on the struct/enum with multi-type `derive` items",
            ));
        }

        let derives = if let Some(path) = opts.path {
            let path_span = path.span();
            let ignore_extra = opts.ignore_extra.is_present().then(|| opts.ignore_extra.span());
            vec![DeriveConfig {
                path: Located::new(path.into_inner().into_inner(), path_span),
                from: map_derive_input(opts.from.as_ref()),
                into: map_derive_input(opts.into.as_ref()),
                try_from: map_derive_input(opts.try_from.as_ref()),
                try_into: map_derive_input(opts.try_into.as_ref()),
                add: opts.add.into_iter().map(AddedField::from).collect(),
                ignore_extra,
            }]
        } else {
            opts.items.into_iter().map(DeriveConfig::from).collect()
        };

        let local_data = match opts.data {
            Data::Struct(fields) => {
                let mut local_fields = Vec::new();
                for f in fields.fields {
                    local_fields.push(BaseField::try_from(f)?);
                }
                BaseData::Struct(local_fields)
            }
            Data::Enum(variants) => {
                let mut local_variants = Vec::new();
                for v in variants {
                    local_variants.push(BaseVariant::try_from(v)?);
                }
                BaseData::Enum(local_variants)
            }
        };

        Ok(MappingSpec {
            ident: opts.ident,
            generics: opts.generics,
            data: local_data,
            derives,
        })
    }
}

impl From<ItemInput> for DeriveConfig {
    fn from(item: ItemInput) -> Self {
        let path_span = item.path.span();
        let ignore_extra = item.ignore_extra.is_present().then(|| item.ignore_extra.span());

        DeriveConfig {
            path: Located::new(item.path.into_inner().into_inner(), path_span),
            from: map_derive_input(item.from.as_ref()),
            into: map_derive_input(item.into.as_ref()),
            try_from: map_derive_input(item.try_from.as_ref()),
            try_into: map_derive_input(item.try_into.as_ref()),
            add: item.add.into_iter().map(AddedField::from).collect(),
            ignore_extra,
        }
    }
}

impl TryFrom<VariantReceiver> for BaseVariant {
    type Error = Error;

    fn try_from(rec: VariantReceiver) -> Result<Self, Self::Error> {
        let VariantReceiver {
            ident: _,
            discriminant: _,
            fields: _,
            items: _,
            path: rec_path,
            rename: rec_rename,
            add: rec_add,
            skip: rec_skip,
            ignore_extra: rec_ignore_extra,
        } = &rec;

        let has_single_type_variant_opts = rec_path.is_some()
            || rec_rename.is_some()
            || !rec_add.is_empty()
            || rec_skip.is_some()
            || rec_ignore_extra.is_present();

        let has_multi_type_variant = !rec.items.is_empty();

        if has_single_type_variant_opts && has_multi_type_variant {
            let err_span = rec
                .path
                .as_ref()
                .map(SpannedValue::span)
                .or_else(|| rec.rename.as_ref().map(SpannedValue::span))
                .or_else(|| rec.add.first().map(|a| a.field.span()))
                .or_else(|| rec.skip.as_ref().map(SpannedValue::span))
                .unwrap_or_else(|| rec.ident.span());

            return Err(Error::new(
                err_span,
                "Cannot mix single-type attributes directly on the variant with multi-type `when` items",
            ));
        }

        let mut fields = Vec::new();
        for f in rec.fields.fields {
            fields.push(BaseField::try_from(f)?);
        }

        let raw_attrs = if rec.path.is_some() || !rec.items.is_empty() {
            let mut overrides = Vec::new();
            for item in rec.items {
                overrides.push((
                    (*item.path).clone().into_inner(),
                    VariantMapping {
                        rename: item.rename.as_ref().map(|s| s.as_ref().clone()),
                        add: item.add.into_iter().map(AddedField::from).collect(),
                        skip: map_skip(item.skip.as_ref()),
                        ignore_extra: item.ignore_extra.is_present(),
                    },
                ));
            }
            if let Some(path) = rec.path {
                overrides.push((
                    path.into_inner().into_inner(),
                    VariantMapping {
                        rename: rec.rename.as_ref().map(|s| s.as_ref().clone()),
                        add: rec.add.into_iter().map(AddedField::from).collect(),
                        skip: map_skip(rec.skip.as_ref()),
                        ignore_extra: rec.ignore_extra.is_present(),
                    },
                ));
            }
            VariantMappings::Overrides(overrides)
        } else {
            VariantMappings::Default(Box::new(VariantMapping {
                rename: rec.rename.as_ref().map(|s| s.as_ref().clone()),
                add: rec.add.clone().into_iter().map(AddedField::from).collect(),
                skip: map_skip(rec.skip.as_ref()),
                ignore_extra: rec.ignore_extra.is_present(),
            }))
        };

        Ok(Self {
            ident: rec.ident,
            fields,
            mappings: raw_attrs,
        })
    }
}

impl TryFrom<FieldReceiver> for BaseField {
    type Error = Error;

    fn try_from(rec: FieldReceiver) -> Result<Self, Self::Error> {
        let FieldReceiver {
            ident: _,
            vis: _,
            ty: _,
            items: _,
            path: rec_path,
            rename: rec_rename,
            skip: rec_skip,
            other_ty: rec_other_ty,
            hint:
                MapperHint {
                    with: hint_with,
                    into_with: hint_into_with,
                    from_with: hint_from_with,
                    opt: hint_opt,
                    iter: hint_iter,
                    map: hint_map,
                    boxed: hint_boxed,
                    r#box: hint_box,
                    unbox: hint_unbox,
                },
            err: rec_err,
            err_with: rec_err_with,
        } = &rec;

        let has_hint = hint_with.is_some()
            || hint_into_with.is_some()
            || hint_from_with.is_some()
            || hint_opt.is_some()
            || hint_iter.is_some()
            || hint_map.is_some()
            || hint_boxed.is_some()
            || hint_box.is_some()
            || hint_unbox.is_some();

        let has_single_type_field_opts = rec_path.is_some()
            || rec_rename.is_some()
            || rec_skip.is_some()
            || rec_other_ty.is_some()
            || has_hint
            || rec_err.is_some()
            || rec_err_with.is_some();

        let has_multi_type_field = !rec.items.is_empty();

        if has_single_type_field_opts && has_multi_type_field {
            let err_span = rec
                .path
                .as_ref()
                .map(SpannedValue::span)
                .or_else(|| rec.rename.as_ref().map(SpannedValue::span))
                .or_else(|| rec.skip.as_ref().map(SpannedValue::span))
                .or_else(|| rec.other_ty.as_ref().map(SpannedValue::span))
                .unwrap_or_else(|| rec.ident.as_ref().map(Ident::span).unwrap_or_else(|| rec.ty.span()));

            return Err(Error::new(
                err_span,
                "Cannot mix single-type attributes directly on the field with multi-type `when` items",
            ));
        }

        let raw_attrs = if rec.path.is_some() || !rec.items.is_empty() {
            let mut overrides = Vec::new();
            for item in rec.items {
                let item_span = item
                    .rename
                    .as_ref()
                    .map(SpannedValue::span)
                    .unwrap_or_else(|| item.path.span());

                overrides.push((
                    (*item.path).clone().into_inner(),
                    Located::new(
                        FieldMapping {
                            rename: item.rename.as_ref().map(|s| s.as_ref().clone()),
                            skip: map_skip(item.skip.as_ref()),
                            other_ty: item.other_ty.as_ref().map(|s| s.as_ref().clone()),
                            hint: TransformHint::from(item.hint),
                            err: item.err.as_ref().map(|e| e.as_ref().clone()),
                            err_with: item.err_with.as_ref().map(|e| e.as_ref().clone()),
                        },
                        item_span,
                    ),
                ));
            }

            if let Some(path) = rec.path {
                let path_span = path.span();
                overrides.push((
                    path.into_inner().into_inner(),
                    Located::new(
                        FieldMapping {
                            rename: rec.rename.as_ref().map(|s| s.as_ref().clone()),
                            skip: map_skip(rec.skip.as_ref()),
                            other_ty: rec.other_ty.as_ref().map(|s| s.as_ref().clone()),
                            hint: TransformHint::from(rec.hint.clone()),
                            err: rec.err.as_ref().map(|e| e.as_ref().clone()),
                            err_with: rec.err_with.as_ref().map(|e| e.as_ref().clone()),
                        },
                        path_span,
                    ),
                ));
            }
            FieldMappings::Overrides(overrides)
        } else {
            let span = rec.ident.as_ref().map(Ident::span).unwrap_or_else(|| rec.ty.span());
            FieldMappings::Default(Box::new(Located::new(
                FieldMapping {
                    rename: rec.rename.as_ref().map(|s| s.as_ref().clone()),
                    skip: map_skip(rec.skip.as_ref()),
                    other_ty: rec.other_ty.as_ref().map(|s| s.as_ref().clone()),
                    hint: TransformHint::from(rec.hint),
                    err: rec.err.as_ref().map(|e| e.as_ref().clone()),
                    err_with: rec.err_with.as_ref().map(|e| e.as_ref().clone()),
                },
                span,
            )))
        };

        Ok(Self {
            ident: rec.ident,
            ty: rec.ty,
            mappings: raw_attrs,
        })
    }
}

impl From<MapperHint> for TransformHint {
    fn from(hint: MapperHint) -> Self {
        let map_spanned_expr = |opt: Option<SpannedValue<Expr>>| -> Option<Located<Expr>> {
            opt.map(|sv| {
                let span = sv.span();
                Located::new(sv.into_inner(), span)
            })
        };

        let map_boxed_hint =
            |opt: Option<SpannedValue<Override<Box<MapperHint>>>>| -> Option<Located<Box<TransformHint>>> {
                opt.map(|spanned| {
                    let span = spanned.span();
                    let inner = match spanned.into_inner() {
                        Override::Inherit => Box::new(TransformHint::default()),
                        Override::Explicit(boxed_hint) => Box::new(TransformHint::from(*boxed_hint)),
                    };
                    Located::new(inner, span)
                })
            };

        TransformHint {
            with: map_spanned_expr(hint.with),
            into_with: map_spanned_expr(hint.into_with),
            from_with: map_spanned_expr(hint.from_with),
            opt: map_boxed_hint(hint.opt),
            iter: map_boxed_hint(hint.iter),
            map: map_boxed_hint(hint.map),
            boxed: map_boxed_hint(hint.boxed),
            r#box: map_boxed_hint(hint.r#box),
            unbox: map_boxed_hint(hint.unbox),
        }
    }
}

fn map_derive_input(opt: Option<&SpannedValue<Override<DeriveInput>>>) -> Option<ConversionOptions> {
    opt.map(|spanned| match spanned.as_ref() {
        Override::Inherit => ConversionOptions {
            custom: None,
            err: None,
            accumulate: None,
        },
        Override::Explicit(derive) => {
            let custom = derive.custom.as_ref().map(|c| {
                let custom_span = c.span();
                let value = match c.as_ref() {
                    Override::Inherit => None,
                    Override::Explicit(ident) => Some(ident.clone()),
                };
                Located::new(value, custom_span)
            });

            let accumulate = derive.accumulate.as_ref().map(|a| {
                let acc_span = a.span();
                let value = match a.as_ref() {
                    Override::Inherit => None,
                    Override::Explicit(wrapper) => Some((*wrapper).clone().into_inner()),
                };
                Located::new(value, acc_span)
            });

            ConversionOptions {
                custom,
                err: derive.err.as_ref().map(|w| (*w).clone().into_inner()),
                accumulate,
            }
        }
    })
}

impl From<AddInput> for AddedField {
    fn from(add: AddInput) -> Self {
        let field_span = add.field.span();
        let field = Located::new(add.field.into_inner(), field_span);

        let ty = add.ty.map(|t| {
            let ty_span = t.span();
            Located::new(t.into_inner().into_inner(), ty_span)
        });

        let default = add.default.map(|d| {
            let default_span = d.span();
            let value = match d.into_inner() {
                Override::Inherit => parse_quote!(Default::default()),
                Override::Explicit(default_input) => default_input.value,
            };
            Located::new(value, default_span)
        });

        AddedField { field, ty, default }
    }
}

fn map_skip(opt: Option<&SpannedValue<Override<SkipInput>>>) -> Option<Located<SkippedField>> {
    opt.map(|spanned| {
        let span = spanned.span();
        let default = match spanned.as_ref() {
            Override::Inherit => None,
            Override::Explicit(skip) => {
                if let Some(d) = &skip.default {
                    let default_span = d.span();
                    let value = match d.as_ref() {
                        Override::Inherit => parse_quote!(Default::default()),
                        Override::Explicit(default_input) => default_input.value.clone(),
                    };
                    Some(Located::new(value, default_span))
                } else {
                    None
                }
            }
        };

        Located::new(SkippedField { default }, span)
    })
}

#[cfg(test)]
mod tests {
    use quote::ToTokens as _;
    use syn::{DeriveInput as SynDeriveInput, parse_quote};

    use super::*;

    #[test]
    fn mapper_opts_mixed_error() {
        let input: SynDeriveInput = parse_quote! {
            #[mapper(ty = "Target", derive(ty = "Other"))]
            struct Source {
                field: String,
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let res = MappingSpec::try_from(opts);
        let Err(err) = res else {
            panic!("expected Err");
        };
        assert!(err.to_string().contains("Cannot mix single-type attributes"));
    }

    #[test]
    fn variant_receiver_mixed_error() {
        let input: SynDeriveInput = parse_quote! {
            enum Source {
                #[mapper(ty = "Target", when(ty = "Other"))]
                Variant1,
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let res = MappingSpec::try_from(opts);
        let Err(err) = res else {
            panic!("expected Err");
        };
        assert!(err.to_string().contains("Cannot mix single-type attributes"));
    }

    #[test]
    fn field_receiver_mixed_error() {
        let input: SynDeriveInput = parse_quote! {
            struct Source {
                #[mapper(ty = "Target", when(ty = "Other"))]
                field: String,
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let res = MappingSpec::try_from(opts);
        let Err(err) = res else {
            panic!("expected Err");
        };
        assert!(err.to_string().contains("Cannot mix single-type attributes"));
    }

    #[test]
    fn struct_single_type_happy_path() {
        let input: SynDeriveInput = parse_quote! {
            #[mapper(
                ty = "Target",
                from(custom),
                into(custom = "to_target"),
                add(field = extra, default(value = 42)),
                add(field = simple_extra, default),
                add(field = typed_extra, ty = "i32", default),
                add(field = no_default_extra, ty = "i32"),
                ignore_extra
            )]
            struct Source {
                #[mapper(rename = "other", other_ty = "OtherIdent", err = "MyError")]
                field1: String,
                #[mapper(skip(default))]
                field2: String,
                #[mapper(opt)]
                field3: Option<String>,
                #[mapper(skip)]
                field4: String,
                #[mapper(skip())]
                field5: String,
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let item = MappingSpec::try_from(opts).expect("MappingSpec try_from should succeed");

        assert_eq!(item.ident, "Source");
        assert_eq!(item.derives.len(), 1);
        let derive = &item.derives[0];
        assert_eq!(
            derive.path.value().to_token_stream().to_string().replace(' ', ""),
            "Target"
        );

        // from(custom) -> custom flag without name
        assert!(
            derive
                .from
                .as_ref()
                .expect("from option should be set")
                .custom
                .as_ref()
                .expect("custom option should be set")
                .value()
                .is_none()
        );
        assert!(derive.into.is_some());

        assert_eq!(derive.add.len(), 4);
        assert_eq!(derive.add[0].field.value(), "extra");
        assert_eq!(derive.add[1].field.value(), "simple_extra");
        assert!(derive.add[1].default.is_some()); // inherits Default::default()
        assert_eq!(derive.add[2].field.value(), "typed_extra");
        assert_eq!(
            derive.add[2]
                .ty
                .as_ref()
                .expect("typed_extra must have a type")
                .value()
                .to_token_stream()
                .to_string()
                .replace(' ', ""),
            "i32"
        );
        assert_eq!(derive.add[3].field.value(), "no_default_extra");
        assert!(derive.add[3].default.is_none());

        assert!(derive.ignore_extra.is_some());

        if let BaseData::Struct(fields) = &item.data {
            assert_eq!(fields.len(), 5);
            assert_eq!(
                fields[0].ident.as_ref().expect("field1 must have an identifier"),
                "field1"
            );
            if let FieldMappings::Default(attr) = &fields[0].mappings {
                assert_eq!(attr.rename.as_ref().expect("rename attribute should be set"), "other");
                assert_eq!(
                    attr.other_ty.as_ref().expect("other_ty attribute should be set"),
                    "OtherIdent"
                );
                assert!(attr.err.is_some());
            } else {
                panic!("expected RawFieldAttrs::Default");
            }
            assert_eq!(
                fields[1].ident.as_ref().expect("field2 must have an identifier"),
                "field2"
            );
            if let FieldMappings::Default(attr) = &fields[1].mappings {
                assert!(attr.skip.is_some());
            } else {
                panic!("expected RawFieldAttrs::Default");
            }

            // field3 has flat opt
            assert_eq!(
                fields[2].ident.as_ref().expect("field3 must have an identifier"),
                "field3"
            );
            if let FieldMappings::Default(attr) = &fields[2].mappings {
                assert!(attr.hint.opt.is_some());
            } else {
                panic!("expected RawFieldAttrs::Default");
            }

            // field4 has flat skip
            assert_eq!(
                fields[3].ident.as_ref().expect("field4 must have an identifier"),
                "field4"
            );
            if let FieldMappings::Default(attr) = &fields[3].mappings {
                assert!(attr.skip.is_some());
                assert!(
                    attr.skip
                        .as_ref()
                        .expect("skip attribute should be set")
                        .default
                        .is_none()
                );
            } else {
                panic!("expected RawFieldAttrs::Default");
            }

            // field5 has skip() without default
            assert_eq!(
                fields[4].ident.as_ref().expect("field5 must have an identifier"),
                "field5"
            );
            if let FieldMappings::Default(attr) = &fields[4].mappings {
                assert!(attr.skip.is_some());
                assert!(
                    attr.skip
                        .as_ref()
                        .expect("skip attribute should be set")
                        .default
                        .is_none()
                );
            } else {
                panic!("expected RawFieldAttrs::Default");
            }
        } else {
            panic!("expected Struct");
        }
    }

    #[test]
    fn enum_multi_type_happy_path() {
        let input: SynDeriveInput = parse_quote! {
            #[mapper(derive(
                ty = "Target1",
                try_from(accumulate, err = "MyDeriveError"),
                try_into
            ))]
            #[mapper(derive(
                ty = "Target2",
                try_from(accumulate = "MyAccumulator"),
                ignore_extra
            ))]
            enum Source {
                #[mapper(when(ty = "Target1", rename = "V1", ignore_extra), when(ty = "Target2", skip(default(value = 100))))]
                Variant1 {
                    #[mapper(when(ty = "Target1", rename = "f1"))]
                    field1: String,
                    #[mapper(when(ty = "Target1"))]
                    field2: String,
                },
                #[mapper(rename = "V2", ignore_extra)]
                Variant2,
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let item = MappingSpec::try_from(opts).expect("MappingSpec try_from should succeed");

        assert_eq!(item.ident, "Source");
        assert_eq!(item.derives.len(), 2);

        let derive1 = &item.derives[0];
        assert_eq!(
            derive1.path.value().to_token_stream().to_string().replace(' ', ""),
            "Target1"
        );
        assert!(derive1.try_from.is_some());
        assert!(derive1.try_into.is_some());
        // accumulate without explicit custom accumulator type
        assert!(
            derive1
                .try_from
                .as_ref()
                .expect("try_from option should be set")
                .accumulate
                .as_ref()
                .expect("accumulate option should be set")
                .value()
                .is_none()
        );
        assert_eq!(
            derive1
                .try_from
                .as_ref()
                .expect("try_from option should be set")
                .err
                .as_ref()
                .expect("err option should be set")
                .to_token_stream()
                .to_string()
                .replace(' ', ""),
            "MyDeriveError"
        );

        let derive2 = &item.derives[1];
        assert_eq!(
            derive2.path.value().to_token_stream().to_string().replace(' ', ""),
            "Target2"
        );
        assert!(derive2.ignore_extra.is_some());
        assert_eq!(
            derive2
                .try_from
                .as_ref()
                .expect("try_from option should be set")
                .accumulate
                .as_ref()
                .expect("accumulate option should be set")
                .value()
                .as_ref()
                .expect("accumulator type should be set")
                .to_token_stream()
                .to_string()
                .replace(' ', ""),
            "MyAccumulator"
        );

        if let BaseData::Enum(variants) = &item.data {
            assert_eq!(variants.len(), 2);
            let var = &variants[0];
            assert_eq!(var.ident, "Variant1");

            if let VariantMappings::Overrides(overrides) = &var.mappings {
                assert_eq!(overrides.len(), 2);
                assert_eq!(overrides[0].0.to_token_stream().to_string().replace(' ', ""), "Target1");
                assert_eq!(
                    overrides[0].1.rename.as_ref().expect("rename attribute should be set"),
                    "V1"
                );
                assert!(overrides[0].1.ignore_extra);

                assert_eq!(overrides[1].0.to_token_stream().to_string().replace(' ', ""), "Target2");
                assert!(overrides[1].1.skip.is_some());
            } else {
                panic!("expected RawVariantAttrs::Overrides");
            }

            assert_eq!(var.fields.len(), 2);
            let field1 = &var.fields[0];
            assert_eq!(field1.ident.as_ref().expect("field1 must have an identifier"), "field1");
            if let FieldMappings::Overrides(field_overrides) = &field1.mappings {
                assert_eq!(field_overrides.len(), 1);
                assert_eq!(
                    field_overrides[0].0.to_token_stream().to_string().replace(' ', ""),
                    "Target1"
                );
                assert_eq!(
                    field_overrides[0]
                        .1
                        .rename
                        .as_ref()
                        .expect("rename override attribute should be set"),
                    "f1"
                );
            } else {
                panic!("expected RawFieldAttrs::Overrides");
            }

            let field2 = &var.fields[1];
            assert_eq!(field2.ident.as_ref().expect("field2 must have an identifier"), "field2");
            if let FieldMappings::Overrides(field_overrides) = &field2.mappings {
                assert_eq!(field_overrides.len(), 1);
                assert_eq!(
                    field_overrides[0].0.to_token_stream().to_string().replace(' ', ""),
                    "Target1"
                );
                assert!(field_overrides[0].1.rename.is_none());
            } else {
                panic!("expected RawFieldAttrs::Overrides");
            }

            // Variant2 check (Default variant path)
            let var2 = &variants[1];
            assert_eq!(var2.ident, "Variant2");
            if let VariantMappings::Default(attr) = &var2.mappings {
                assert_eq!(attr.rename.as_ref().expect("rename attribute should be set"), "V2");
                assert!(attr.ignore_extra);
            } else {
                panic!("expected RawVariantAttrs::Default");
            }
        } else {
            panic!("expected Enum");
        }
    }

    #[test]
    fn single_type_with_explicit_paths() {
        let input: SynDeriveInput = parse_quote! {
            #[mapper(ty = "Target")] // ignore_extra is None here
            enum Source {
                #[mapper(ty = "Target", rename = "V1")]
                Variant1(#[mapper(ty = "Target", rename = "f1", err_with = "map_err")] String)
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let item = MappingSpec::try_from(opts).expect("MappingSpec try_from should succeed");

        assert_eq!(item.derives.len(), 1);
        assert!(item.derives[0].ignore_extra.is_none()); // covers ignore_extra as None branch

        if let BaseData::Enum(variants) = &item.data {
            assert_eq!(variants.len(), 1);
            let var = &variants[0];

            // Covers VariantReceiver path.is_some() branch
            if let VariantMappings::Overrides(overrides) = &var.mappings {
                assert_eq!(overrides.len(), 1);
                assert_eq!(overrides[0].0.to_token_stream().to_string().replace(' ', ""), "Target");
                assert_eq!(
                    overrides[0].1.rename.as_ref().expect("rename attribute should be set"),
                    "V1"
                );
            } else {
                panic!("expected RawVariantAttrs::Overrides");
            }

            // Covers FieldReceiver path.is_some() branch and tuple field ident is None
            assert_eq!(var.fields.len(), 1);
            let field = &var.fields[0];
            assert!(field.ident.is_none()); // tuple field
            if let FieldMappings::Overrides(field_overrides) = &field.mappings {
                assert_eq!(field_overrides.len(), 1);
                assert_eq!(
                    field_overrides[0].0.to_token_stream().to_string().replace(' ', ""),
                    "Target"
                );
                assert_eq!(
                    field_overrides[0]
                        .1
                        .rename
                        .as_ref()
                        .expect("rename override attribute should be set"),
                    "f1"
                );
                assert!(field_overrides[0].1.err_with.is_some()); // covers err_with branch
            } else {
                panic!("expected RawFieldAttrs::Overrides");
            }
        } else {
            panic!("expected Enum");
        }
    }

    #[test]
    fn field_hints_nesting() {
        let input: SynDeriveInput = parse_quote! {
            struct Source {
                #[mapper(opt(iter(boxed(with = "my_fn"))))]
                field: Option<Vec<Box<String>>>,
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let item = MappingSpec::try_from(opts).expect("MappingSpec try_from should succeed");

        if let BaseData::Struct(fields) = &item.data {
            assert_eq!(fields.len(), 1);
            if let FieldMappings::Default(attr) = &fields[0].mappings {
                let opt_hint = attr.hint.opt.as_ref().expect("opt hint should be set");
                let iter_hint = opt_hint.value().iter.as_ref().expect("iter hint should be set");
                let boxed_hint = iter_hint.value().boxed.as_ref().expect("boxed hint should be set");
                let with_expr = boxed_hint.value().with.as_ref().expect("with hint should be set");
                assert_eq!(quote::quote!(#with_expr).to_string(), "my_fn");
            } else {
                panic!("expected RawFieldAttrs::Default");
            }
        } else {
            panic!("expected Struct");
        }
    }

    #[test]
    fn all_hints_parsed() {
        let input: SynDeriveInput = parse_quote! {
            struct Source {
                #[mapper(with = "f1", into_with = "f2", from_with = "f3", opt, iter, map, boxed, box, unbox)]
                field: String,
            }
        };
        let opts = MapperOpts::from_derive_input(&input).expect("MapperOpts parsing from derive input should succeed");
        let item = MappingSpec::try_from(opts).expect("MappingSpec try_from should succeed");

        if let BaseData::Struct(fields) = &item.data {
            assert_eq!(fields.len(), 1);
            if let FieldMappings::Default(attr) = &fields[0].mappings {
                assert!(attr.hint.with.is_some());
                assert!(attr.hint.into_with.is_some());
                assert!(attr.hint.from_with.is_some());
                assert!(attr.hint.opt.is_some());
                assert!(attr.hint.iter.is_some());
                assert!(attr.hint.map.is_some());
                assert!(attr.hint.boxed.is_some());
                assert!(attr.hint.r#box.is_some());
                assert!(attr.hint.unbox.is_some());
            } else {
                panic!("expected RawFieldAttrs::Default");
            }
        } else {
            panic!("expected Struct");
        }
    }
}
