//! Integration tests verifying enum mappings.

#![allow(dead_code, unused, clippy::restriction, reason = "test")]

use std::num::TryFromIntError;

use model_mapper::Mapper;

// ====================================================================================================================
// Shared error type for fallible conversions
// ====================================================================================================================

/// Represents errors returned by our `try_from`/`try_into` mappings.
/// Uses thiserror to cleanly wrap `TryFromIntError` generated by our i8 <-> u8 conversions,
/// completely eliminating the need for `From<Infallible>`.
#[derive(Debug, thiserror::Error, PartialEq, Eq, Clone)]
enum TestEnumError {
    #[error("Conversion error")]
    Failure,
    #[error("Integer conversion error: {0}")]
    IntError(#[from] TryFromIntError),
    #[error("Infallible error")]
    InfallibleError, // This variant is never used but is required to satisfy the `From<Infallible>` bound
}

impl From<std::convert::Infallible> for TestEnumError {
    fn from(_: std::convert::Infallible) -> Self {
        TestEnumError::InfallibleError
    }
}

// ====================================================================================================================
// Unit variant enums (simple C-style enums) mapping directions
// ====================================================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum UnitTarget {
    A,
    B,
    C,
}

#[derive(Mapper, Debug, Clone, Copy, PartialEq, Eq)]
#[mapper(from, into, ty = UnitTarget)]
enum UnitSource {
    A,
    B,
    C,
}

#[derive(Mapper, Debug, Clone, Copy, PartialEq, Eq)]
#[mapper(try_from(err = TestEnumError), try_into(err = TestEnumError), ty = UnitTarget)]
enum UnitSourceTry {
    A,
    B,
    C,
}

#[test]
fn test_unit_enums_happy_path() {
    // from mapping
    assert_eq!(UnitSource::from(UnitTarget::A), UnitSource::A);
    assert_eq!(UnitSource::from(UnitTarget::B), UnitSource::B);

    // into mapping
    let source_a: UnitTarget = UnitSource::A.into();
    assert_eq!(source_a, UnitTarget::A);

    // try_from mapping (no inner fields, so it's practically infallible but validates code gen)
    assert_eq!(
        UnitSourceTry::try_from(UnitTarget::A).expect("try_from conversion should succeed"),
        UnitSourceTry::A
    );

    // try_into mapping
    let try_into_a: Result<UnitTarget, _> = UnitSourceTry::A.try_into();
    assert_eq!(try_into_a.expect("try_into conversion should succeed"), UnitTarget::A);
}

// ====================================================================================================================
// Complex enums (tuple / unnamed fields) mapping directions
// ====================================================================================================================

// --- Infallible Mapping Targets (String, i32) ---

#[derive(Debug, Clone, PartialEq, Eq)]
struct TargetPayload(String, i32);

#[derive(Debug, Clone, PartialEq, Eq)]
enum TupleTarget {
    X(String, i32),
    Y(TargetPayload),
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(from, into, ty = TargetPayload)]
struct SourcePayload(String, i32);

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(from, into, ty = TupleTarget)]
enum TupleSource {
    X(String, i32),
    Y(SourcePayload),
}

// --- Fallible Mapping Targets (u8, i8) ---

#[derive(Debug, Clone, PartialEq, Eq)]
struct TargetPayloadTry(u8, i8);

#[derive(Debug, Clone, PartialEq, Eq)]
enum TupleTargetTry {
    X(u8, i8),
    Y(TargetPayloadTry),
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(try_from(err = TestEnumError), try_into(err = TestEnumError), ty = TargetPayloadTry)]
struct SourcePayloadTry(i8, u8); // Swapped sign to trigger fallible conversion

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(try_from(err = TestEnumError), try_into(err = TestEnumError), ty = TupleTargetTry)]
enum TupleSourceTry {
    X(i8, u8),
    Y(SourcePayloadTry),
}

#[test]
fn test_tuple_enums_infallible() {
    let target_x = TupleTarget::X("hello".to_string(), 42);
    let source_x = TupleSource::X("hello".to_string(), 42);

    assert_eq!(TupleSource::from(target_x.clone()), source_x);
    let mapped_x: TupleTarget = source_x.into();
    assert_eq!(mapped_x, target_x);
}

#[test]
fn test_tuple_enums_fallible() {
    // Happy path (values within valid range for both u8 and i8: 0..=127)
    let target_happy = TupleTargetTry::X(42, 42);
    let source_happy = TupleSourceTry::X(42, 42);

    assert_eq!(
        TupleSourceTry::try_from(target_happy.clone()).expect("try_from conversion should succeed"),
        source_happy
    );
    let mapped_x: TupleTargetTry = source_happy
        .clone()
        .try_into()
        .expect("try_into conversion should succeed");
    assert_eq!(mapped_x, target_happy);

    // Error path (u8 -> i8 fails if > 127)
    let target_err = TupleTargetTry::X(200, 42);
    assert!(TupleSourceTry::try_from(target_err).is_err());

    // Error path (i8 -> u8 fails if < 0)
    let source_err = TupleSourceTry::X(-5, 42);
    let err_res: Result<TupleTargetTry, _> = source_err.try_into();
    assert!(err_res.is_err());
}

// ====================================================================================================================
// Complex enums (named fields) mapping directions
// ====================================================================================================================

// --- Infallible Mapping Targets ---

#[derive(Debug, Clone, PartialEq, Eq)]
struct TargetInner {
    val: i64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum NamedTarget {
    Alpha { s: String, inner: TargetInner },
    Beta { count: usize },
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(from, into, ty = TargetInner)]
struct SourceInner {
    val: i64,
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(from, into, ty = NamedTarget)]
enum NamedSource {
    Alpha { s: String, inner: SourceInner },
    Beta { count: usize },
}

// --- Fallible Mapping Targets ---

#[derive(Debug, Clone, PartialEq, Eq)]
struct TargetInnerTry {
    val: u8,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum NamedTargetTry {
    Alpha { s: u8, inner: TargetInnerTry },
    Beta { count: u8 },
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(try_from(err = TestEnumError), try_into(err = TestEnumError), ty = TargetInnerTry)]
struct SourceInnerTry {
    val: i8,
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(try_from(err = TestEnumError), try_into(err = TestEnumError), ty = NamedTargetTry)]
enum NamedSourceTry {
    Alpha { s: i8, inner: SourceInnerTry },
    Beta { count: i8 },
}

#[test]
fn test_named_enums_infallible() {
    let target_alpha = NamedTarget::Alpha {
        s: "test".to_string(),
        inner: TargetInner { val: 123 },
    };
    let source_alpha = NamedSource::Alpha {
        s: "test".to_string(),
        inner: SourceInner { val: 123 },
    };

    assert_eq!(NamedSource::from(target_alpha.clone()), source_alpha);
    let mapped_alpha: NamedTarget = source_alpha.into();
    assert_eq!(mapped_alpha, target_alpha);
}

#[test]
fn test_named_enums_fallible() {
    // Happy path
    let target_beta = NamedTargetTry::Beta { count: 100 };
    let source_beta = NamedSourceTry::Beta { count: 100 };

    assert_eq!(
        NamedSourceTry::try_from(target_beta.clone()).expect("try_from conversion should succeed"),
        source_beta
    );
    let mapped_beta: NamedTargetTry = source_beta
        .clone()
        .try_into()
        .expect("try_into conversion should succeed");
    assert_eq!(mapped_beta, target_beta);

    // Error path (Fails mapping u8 -> i8)
    let target_err = NamedTargetTry::Alpha {
        s: 250,
        inner: TargetInnerTry { val: 10 },
    };
    assert!(NamedSourceTry::try_from(target_err).is_err());
}

// ====================================================================================================================
// Mixed enums mapping directions
// ====================================================================================================================

// --- Infallible Mapping Targets ---

#[derive(Debug, Clone, PartialEq, Eq)]
enum MixedTarget {
    Void,
    Tuple(String, bool),
    Named { id: u64, name: String },
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(from, into, ty = MixedTarget)]
enum MixedSource {
    Void,
    Tuple(String, bool),
    Named { id: u64, name: String },
}

// --- Fallible Mapping Targets ---

#[derive(Debug, Clone, PartialEq, Eq)]
enum MixedTargetTry {
    Void,
    Tuple(u8, bool),
    Named { id: u8, name: u8 },
}

#[derive(Mapper, Debug, Clone, PartialEq, Eq)]
#[mapper(try_from(err = TestEnumError), try_into(err = TestEnumError), ty = MixedTargetTry)]
enum MixedSourceTry {
    Void,
    Tuple(i8, bool),
    Named { id: i8, name: i8 },
}

#[test]
fn test_mixed_enums_infallible() {
    let target = MixedTarget::Named {
        id: 7,
        name: "bob".to_string(),
    };
    let source = MixedSource::Named {
        id: 7,
        name: "bob".to_string(),
    };

    assert_eq!(MixedSource::from(target.clone()), source);
    let mapped: MixedTarget = source.into();
    assert_eq!(mapped, target);
}

#[test]
fn test_mixed_enums_fallible() {
    // Error path Target -> Source
    let target_err = MixedTargetTry::Named { id: 255, name: 10 };
    assert!(MixedSourceTry::try_from(target_err).is_err());

    // Error path Source -> Target
    let source_err = MixedSourceTry::Tuple(-10, true);
    let err_res: Result<MixedTargetTry, _> = source_err.try_into();
    assert!(err_res.is_err());
}
